version: '3.1'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-blueocean:latest
    restart: on-failure
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: 1
    volumes:
      - ./data:/var/jenkins_home
      - ./docker-certs:/certs/client:ro

  jenkins-docker:
    container_name: jenkins-docker
    hostname: docker
    image: docker:dind
    restart: on-failure
    privileged: true
    ports:
      - 2376:2376
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
    volumes:
      - ./data:/var/jenkins_home
      - ./docker-certs:/certs/client
    command: --storage-driver overlay2

networks:
  default:
    name: jenkins

